name: Continuous Integration

# 트리거 설정 - main 브랜치에 push 이벤트 발생시
on:
  push:
    branches:
      - main

# 동시성 방지 - push 중에 새로운 push 이벤트가 발생하면 현재 작업을 멈추고 새로운 작업을 시작하도록
concurrency:
  group: main
  cancel-in-progress: true

# 수행할 작업
jobs:
  deploy:
    name: 배포
    runs-on: ubuntu-latest
    steps:
      - name: 서버컴 SSH 접속
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/cicd
          chmod 600 ~/.ssh/cicd
          cat >>~/.ssh/config <<END
          HOST target
            HostName $SSH_HOST
            USER $SSH_USER
            IdentityFile ~/.ssh/cicd
            LogLevel ERROR
            StrictHostKeyChecking no
          END
      - name: 배포 작업
        run: |
          ssh target "cd /home/saemi/src/project_2/Core && \
          docker-compose down && \
          git pull && \
          docker-compose build && \
          docker-compose -d --force-recreate"
